# name of our pipline
name: app-ci-pipline
#global environment variables for our pipline
env:
    AWS_ACCESS_KRY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    
on:
    push:
        branches:
            - master
        paths:
            - 'Dockerfile'
            - '.github/workflows/**'
            - '.deploy/**'
            - 'src/**'
    pull_request:
        branches:
            - master
jobs:
    test:
        name: Run api tests with Mocha
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16
              uses: actions/setup-node@v2
              with:
                node-version: '16'
            - run: npm ci
            - run: npm test
    build-and-push-docker-image:
        name: build and push docker image
        runs-on: ubuntu-latest
        needs: test
        environment: app-stage
        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v2
            - run: docker login --username ${{ secrets.DOCKER_USEERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            - run: docker build -t 3444866/nomad . 
            - run: docker push 3444866/nomad
    build-ami:
        name: Build AMI images
        env:
            PKR_VAR_docker_username: ${{ secrets.DOCKER_USEERNAME }}
            PKR_VAR_docker_password: ${{  secrets.DOCKER_PASSWORD }}
        environment: app-stage
        runs-on: ubunut-latest
        needs: build-and-push-docker-image
        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v2
            - run: bash .deploy/scripts/packer-install.sh
            - run: cd .deploy/packer && packer validate image.pkr.hcl
            - name: build ami image
              run: cd .deploy/packer && packer build image.pkr.hcl